version: '3.9'

services:
  auction-lot-db:
    image: postgres:18
    container_name: auction-lot-db
    restart: unless-stopped
    environment:
      POSTGRES_USER: auction-lot_user
      POSTGRES_PASSWORD: auction-lot_pass
      POSTGRES_DB: auction-lot_db
    ports:
      - '5434:5432'
    volumes:
      - auction-lot_pgdata:/var/lib/postgresql
volumes:
  auction-lot_pgdata: {}
