// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auctionLotTableQuery.sql

package auctionLotTableQuery

import (
	"context"
)

const createLot = `-- name: CreateLot :exec
insert into lots(title,description) values($1,$2)
`

type CreateLotParams struct {
	Title       string
	Description string
}

func (q *Queries) CreateLot(ctx context.Context, arg CreateLotParams) error {
	_, err := q.db.Exec(ctx, createLot, arg.Title, arg.Description)
	return err
}
