// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auctionLotTableQuery.sql

package auctionLotTableQuery

import (
	"context"

	"github.com/google/uuid"
)

const createLot = `-- name: CreateLot :one
insert into lots(title,description,category,bid_opening_price) values($1,$2,$3,$4) returning id
`

type CreateLotParams struct {
	Title           string
	Description     string
	Category        *string
	BidOpeningPrice *int32
}

func (q *Queries) CreateLot(ctx context.Context, arg CreateLotParams) (uuid.UUID, error) {
	row := q.db.QueryRow(ctx, createLot,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.BidOpeningPrice,
	)
	var id uuid.UUID
	err := row.Scan(&id)
	return id, err
}
