// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: auctionLotTableQuery.sql

package auctionLotTableQuery

import (
	"context"
)

const createLot = `-- name: CreateLot :exec
insert into lots(title,description,category,bid_opening_price) values($1,$2,$3,$4)
`

type CreateLotParams struct {
	Title           string
	Description     string
	Category        *string
	BidOpeningPrice *int32
}

func (q *Queries) CreateLot(ctx context.Context, arg CreateLotParams) error {
	_, err := q.db.Exec(ctx, createLot,
		arg.Title,
		arg.Description,
		arg.Category,
		arg.BidOpeningPrice,
	)
	return err
}
