// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: image_blobs_table.sql

package auctionLotTableQuery

import (
	"context"
)

const checkIdenticalBlobs = `-- name: CheckIdenticalBlobs :many
select image_blob_id,sha256 from public.image_blobs where is_upload_completed=true
`

type CheckIdenticalBlobsRow struct {
	ImageBlobID int64
	Sha256      []byte
}

func (q *Queries) CheckIdenticalBlobs(ctx context.Context) ([]CheckIdenticalBlobsRow, error) {
	rows, err := q.db.Query(ctx, checkIdenticalBlobs)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CheckIdenticalBlobsRow
	for rows.Next() {
		var i CheckIdenticalBlobsRow
		if err := rows.Scan(&i.ImageBlobID, &i.Sha256); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
