// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lot_image_insert.sql

package auctionLotTableQuery

import (
	"context"

	"github.com/google/uuid"
)

const insertAndValidateMultiPartUpload = `-- name: InsertAndValidateMultiPartUpload :many












insert into image_blob_upload_attempts(
  sha256, file_size, content_type, upload_type, 
  upload_id, part_size, lot_id, file_name, 
  username, storage_key
) 
select 
  decode(i.sha256, 'hex') sha256, 
  i.file_size, 
  i.content_type, 
  $1 :: upload_type, 
  i.upload_id, 
  $2 :: bigint, 
  $3 :: uuid, 
  i.file_name, 
  $4 :: varchar(128), 
  i.storage_key 
from 
  unnest(
    $5 :: char(64) [], 
  $6 :: int[], 
  $7 :: text[], 
  $8 :: text[], 
  
    $9 :: varchar(250) []
  , 
  $10 :: uuid[]) i(
    sha256, file_size, content_type, upload_id, 
    file_name, storage_key
  ) on conflict (sha256, lot_id) 
where 
  upload_state = 'pending' do 
update 
set 
  part_size = case when image_blob_upload_attempts.valid_until >= transaction_timestamp() then image_blob_upload_attempts.part_size else $2 :: bigint end, 
  valid_until = case when image_blob_upload_attempts.valid_until >= transaction_timestamp() then image_blob_upload_attempts.valid_until else transaction_timestamp()+ interval '5 days' end 
returning 
  part_size, 
  image_blob_upload_attempt_id, 
  encode(sha256,'hex') sha256, 
  storage_key, 
  upload_id,
    ARRAY(
    SELECT
      generate_series(1, part_count, 1)
  )::smallint[] AS parts,
  (old is null):: boolean as is_inserted, 
coalesce(old.valid_until >=Now(),false)::boolean as is_valid
`

type InsertAndValidateMultiPartUploadParams struct {
	UploadType   UploadType
	PartSize     int64
	LotID        uuid.UUID
	Username     string
	Sha256s      []string
	FileSizes    []int32
	ContentTypes []string
	UploadIds    []string
	FileNames    []string
	StorageKeys  []uuid.UUID
}

type InsertAndValidateMultiPartUploadRow struct {
	PartSize                 *int64
	ImageBlobUploadAttemptID int64
	Sha256                   string
	StorageKey               uuid.UUID
	UploadID                 *string
	Parts                    []int16
	IsInserted               bool
	IsValid                  bool
}

// SELECT
// image_blob_upload_attempt_id,
//
//	encode(sha256, 'hex') AS sha256,
//	upload_id,
//	valid_until,
//	file_size,
//	part_size,
//	storage_key,
//	ARRAY(
//	  SELECT
//	    generate_series(1, part_count, 1)
//	)::smallint[] AS parts
//
// FROM
//
//	image_blob_upload_attempts
//
// WHERE
//
//	sha256 = ANY (
//	  SELECT
//	    decode(i.sha256, 'hex') AS sha256
//	  FROM
//	    unnest(@sha256s::char(64)[]) i(sha256)
//	)
//	AND lot_id = @lot_id::uuid
//	AND upload_type = 'multiUpload'::upload_type
//	AND upload_state = 'pending'::upload_state
//
// FOR UPDATE;
// update  image_blob_upload_attempts iba
// set upload_id=input.upload_id,
//
//	valid_until=default,
//	part_size=input.part_size
//
// from
// (
//
//	select m.upload_id,m.image_blob_upload_attempt_id,@part_size::bigint from
//	unnest(@upload_ids::text[]),unnest(@image_blob_upload_attempt_ids::bigint[])
//
// m(upload_id,image_blob_upload_attempt_id)
// ) as input
//
//	where iba.image_blob_upload_attempt_id=input.image_blob_upload_attempt_id;
//
// insert into image_blob_upload_attempts(sha256,file_size,content_type,upload_type,upload_id,part_size,lot_id,file_name,username,storage_key)
// select  decode(i.sha256, 'hex') sha256, i.file_size,i.content_type,@upload_type::upload_type,i.upload_id,@part_size::bigint,@lot_id::uuid,i.file_name,
// @username::varchar(128), i.storage_key from
// unnest(
// @sha256s::char(64)[]),unnest(@file_sizes::int[]),unnest(@content_types::text[]),unnest(@upload_ids::text[]),
// unnest(@file_names::varchar(250)[]), unnest(@storage_keys::uuid[])  i(sha256,file_size,content_type,upload_id,file_name,storage_key)
// on conflict (sha256,lot_id) where upload_state='pending' do update
// set storage_key=image_blob_upload_attempts.storage_key returning sha256,storage_key,upload_id,(old is null)::boolean as is_inserted;
func (q *Queries) InsertAndValidateMultiPartUpload(ctx context.Context, arg InsertAndValidateMultiPartUploadParams) ([]InsertAndValidateMultiPartUploadRow, error) {
	rows, err := q.db.Query(ctx, insertAndValidateMultiPartUpload,
		arg.UploadType,
		arg.PartSize,
		arg.LotID,
		arg.Username,
		arg.Sha256s,
		arg.FileSizes,
		arg.ContentTypes,
		arg.UploadIds,
		arg.FileNames,
		arg.StorageKeys,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InsertAndValidateMultiPartUploadRow
	for rows.Next() {
		var i InsertAndValidateMultiPartUploadRow
		if err := rows.Scan(
			&i.PartSize,
			&i.ImageBlobUploadAttemptID,
			&i.Sha256,
			&i.StorageKey,
			&i.UploadID,
			&i.Parts,
			&i.IsInserted,
			&i.IsValid,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertIdenticalImageBlobsToLotImages = `-- name: InsertIdenticalImageBlobsToLotImages :many
WITH file_uploads
     (
          sha256,
          file_name,
          lot_id
     )
     AS
     (
            SELECT sha256,
                   file_name,
                   $1::uuid
            FROM   unnest($2::char(64)[],$3::varchar(250)[]) i(sha256,file_name)
                --    unnest(@file_names::varchar(250)[]) i(sha256,file_name)
     )
     ,
     lot_image_inserts AS
     (
                 INSERT INTO lot_images
                             (
                                         lot_id,
                                         image_blob_id,
                                         file_name
                             )
                 SELECT file_uploads.lot_id,
                        image_blobs.image_blob_id,
                        file_uploads.file_name
                 FROM   file_uploads
                 JOIN   image_blobs
                 ON     image_blobs.sha256 = decode(file_uploads.sha256, 'hex')
                 WHERE  image_blobs.is_upload_completed returning lot_image_id,
                        file_name,
                        image_blob_id
     )
SELECT i.lot_image_id,
       i.file_name,
       i.image_blob_id,
       encode(ib.sha256,'hex') sha256
FROM   lot_image_inserts i
JOIN   image_blobs ib
ON     i.image_blob_id=ib.image_blob_id
`

type InsertIdenticalImageBlobsToLotImagesParams struct {
	LotID     uuid.UUID
	Sha256s   []string
	FileNames []string
}

type InsertIdenticalImageBlobsToLotImagesRow struct {
	LotImageID  int64
	FileName    string
	ImageBlobID int64
	Sha256      string
}

func (q *Queries) InsertIdenticalImageBlobsToLotImages(ctx context.Context, arg InsertIdenticalImageBlobsToLotImagesParams) ([]InsertIdenticalImageBlobsToLotImagesRow, error) {
	rows, err := q.db.Query(ctx, insertIdenticalImageBlobsToLotImages, arg.LotID, arg.Sha256s, arg.FileNames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InsertIdenticalImageBlobsToLotImagesRow
	for rows.Next() {
		var i InsertIdenticalImageBlobsToLotImagesRow
		if err := rows.Scan(
			&i.LotImageID,
			&i.FileName,
			&i.ImageBlobID,
			&i.Sha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const insertSinglePartUpload = `-- name: InsertSinglePartUpload :many
INSERT INTO image_blob_upload_attempts
            (
                        sha256,
                        file_size,
                        content_type,
                        upload_type,
                        lot_id,
                        file_name,
                        username
            )
SELECT Decode(i.sha256,'hex'),
       i.file_size,
       i.content_type,
       $1::upload_type,
       $2::     uuid,
       i.file_name,
       $3::text
FROM   unnest( $4::char(64)[],$5::int[],$6:: text[],$7::text[]) i(sha256,file_size,content_type,file_name)
ON conflict (sha256,lot_id)
WHERE  upload_state='pending'
do update  set storage_key=image_blob_upload_attempts.storage_key returning encode(sha256, 'hex') sha256,storage_key,(old is null)::boolean as is_inserted
`

type InsertSinglePartUploadParams struct {
	UploadType   UploadType
	LotID        uuid.UUID
	Username     string
	Sha256s      []string
	FileSizes    []int32
	ContentTypes []string
	FilesNames   []string
}

type InsertSinglePartUploadRow struct {
	Sha256     string
	StorageKey uuid.UUID
	IsInserted bool
}

func (q *Queries) InsertSinglePartUpload(ctx context.Context, arg InsertSinglePartUploadParams) ([]InsertSinglePartUploadRow, error) {
	rows, err := q.db.Query(ctx, insertSinglePartUpload,
		arg.UploadType,
		arg.LotID,
		arg.Username,
		arg.Sha256s,
		arg.FileSizes,
		arg.ContentTypes,
		arg.FilesNames,
	)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InsertSinglePartUploadRow
	for rows.Next() {
		var i InsertSinglePartUploadRow
		if err := rows.Scan(&i.Sha256, &i.StorageKey, &i.IsInserted); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
