// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: lot_image_insert.sql

package auctionLotTableQuery

import (
	"context"

	"github.com/google/uuid"
)

const insertIdenticalImageBlobsToLotImages = `-- name: InsertIdenticalImageBlobsToLotImages :many
with file_uploads(sha256, lot_id, filename) as (
select
unnest($1::char(64)[]),
unnest($2::uuid[]),
unnest($3::varchar(250)[])
	),
 lot_image_inserts as (
insert
	into
		lot_images(lot_id, image_blob_id, filename)
		select
			file_uploads.lot_id,
			image_blobs.image_blob_id,
			file_uploads.filename
		from
			file_uploads
		join 
 image_blobs on
			image_blobs.sha256 = decode(file_uploads.sha256, 'hex')
		where
			image_blobs.is_upload_completed returning lot_image_id,
			filename,
			image_blob_id)
 
 select i.lot_image_id,i.filename,i.image_blob_id,encode(ib.sha256,'hex') sha256 from lot_image_inserts i join image_blobs ib on i.image_blob_id=ib.image_blob_id
`

type InsertIdenticalImageBlobsToLotImagesParams struct {
	Sha256s   []string
	Lotids    []uuid.UUID
	Filenames []string
}

type InsertIdenticalImageBlobsToLotImagesRow struct {
	LotImageID  int64
	Filename    string
	ImageBlobID int64
	Sha256      string
}

func (q *Queries) InsertIdenticalImageBlobsToLotImages(ctx context.Context, arg InsertIdenticalImageBlobsToLotImagesParams) ([]InsertIdenticalImageBlobsToLotImagesRow, error) {
	rows, err := q.db.Query(ctx, insertIdenticalImageBlobsToLotImages, arg.Sha256s, arg.Lotids, arg.Filenames)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []InsertIdenticalImageBlobsToLotImagesRow
	for rows.Next() {
		var i InsertIdenticalImageBlobsToLotImagesRow
		if err := rows.Scan(
			&i.LotImageID,
			&i.Filename,
			&i.ImageBlobID,
			&i.Sha256,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
