// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package auctionLotTableQuery

import (
	"github.com/google/uuid"
)

type Lot struct {
	ID              uuid.UUID
	Title           string
	Description     string
	Category        *string
	BidOpeningPrice *int32
}
